### ISSUE TITLE
Use Automatic ignition events

### ISSUE THREAD

**Issue by rtclauss** [rtclauss/hass-config#9]
https://developer.automatic.com/api-reference/#real-time-events/

```yaml
# Example automatic event automation
automation:
  - trigger:
      - platform: event
        event_type: automatic_update
        event_data:
          type: "ignition:on"
          vehicle:
            id: "C_1234567890abcdefc"
    action:
      - service: light.turn_off
```
